mod_name = "Magnify"
mod_id = "magnify"
mod_group = "org.teamvoided"
mod_version = "1.0.0"
mod_description = "Template Mod Description"
github_repo = "Teamvoided/TeamVoidedTemplateMod"
discord_invite = "https://discord.gg/KZ5Q364hEg"
authors = [ "MincraftEinstein" ]
license = "MIT"
version_range = ">=1.21.1 <1.21.2"
